// -------- Login Actions
export const LOGIN_ATTEMPT = 'Auth/LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'Auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'Auth/LOGIN_FAILURE';
export const LOGOUT = 'Auth/LOGOUT';
export const FORGOT_PASSWORD_EMAIL_SENT = 'Auth/FORGOT_PASSWORD_EMAIL_SENT';
export const FORGOT_PASSWORD_LOADING = 'Auth/FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_ERROR = 'Auth/FORGOT_PASSWORD_ERROR';

// -------- User Actions
export const USERS_RETRIEVED = 'App/USERS_RETRIEVED';
export const SINGLE_USER_RETRIEVED = 'App/SINGLE_USER_RETRIEVED';
export const NEW_USER_CREATED = 'App/NEW_USER_CREATED';
export const ROLES_RETRIEVED = 'App/ROLES_RETRIEVED';
export const NEW_USER_ERROR_RETRIEVED = 'App/NEW_USER_ERROR_RETRIEVED';
export const PASSWORD_RESET = 'App/PASSWORD_RESET';
export const PASSWORD_RESET_ERROR = 'App/PASSWORD_RESET_ERROR';
export const RECIEVE_AUTH_URL = 'App/RECIEVE_AUTH_URL';
export const USER_DELETED = 'App/USER_DELETED';
export const USER_DELETE_ERROR = 'App/USER_DELETE_ERROR';
export const NEW_ROLE_CREATED = 'App/NEW_ROLE_CREATED';
export const NEW_ROLE_ERROR_RETRIEVED = 'App/NEW_ROLE_ERROR_RETRIEVED';

// -------- Upload Actions
export const UPLOAD_PENDING = 'App/UPLOAD_PENDING';
export const UPLOAD_SUCCESS = 'App/UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'App/UPLOAD_ERROR';
export const UPLOAD_DELETE = 'App/UPLOAD_DELETE';

// -------- Playbook Actions
export const PLAYBOOK_RETRIEVED = 'App/PLAYBOOK_RETRIEVED';
export const PLAYBOOK_SELECTED = 'App/PLAYBOOK_SELECTED';
export const SUBMITTED_PLAYBOOK_UPDATE = 'App/SUBMITTED_PLAYBOOK_UPDATE';

// -------- Playbook Editor Actions
export const ADD_SLIDE = 'App/ADD_SLIDE';
export const REMOVE_SLIDE = 'App/REMOVE_SLIDE';
export const SAVING_PLAYBOOK = 'App/SAVING_PLAYBOOK';
export const SINGLE_PLAYBOOK_RETRIEVED = 'App/SINGLE_PLAYBOOK_RETRIEVED';
export const EDIT_SLIDE = 'App/EDIT_SLIDE';
export const PLAYBOOK_ORDER_MODIFIED = 'App/PLAYBOOK_ORDER_MODIFIED';

// -------- Playbook View Actions
export const PLAYBOOKS_RETRIEVED = 'App/PLAYBOOKS_RETRIEVED';
export const PLAYBOOK_ASSIGNMENT_SUCCESS = 'App/PLAYBOOK_ASSIGNMENT_SUCCESS';
export const PLAYBOOK_ASSIGNMENT_PENDING = 'App/PLAYBOOK_ASSIGNMENT_PENDING';
export const ADD_NEW_PLAYBOOK = 'App/ADD_NEW_PLAYBOOK';
export const UPDATE_MESSAGE = 'App/UPDATE_MESSAGE';
export const PLAYBOOK_MODIFIED = 'App/PLAYBOOK_MODIFIED';
export const PLAYBOOK_UNASSIGNMENT_SUCCESS = 'App/PLAYBOOK_UNASSIGNMENT_SUCCESS';

// -------- Email Actions
export const ATTEMPT_SENDING_EMAIL = 'App/ATTEMPT_SENDING_EMAIL';
