// -------- Login Actions
export const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'APP/LOGIN_FAILURE';
export const LOGOUT = 'App/LOGOUT';
export const FORGOT_PASSWORD_EMAIL_SENT = 'App/FORGOT_PASSWORD_EMAIL_SENT';
export const FORGOT_PASSWORD_ERROR = 'App/FORGOT_PASSWORD_ERROR';

// -------- User Actions
export const USERS_RETRIEVED = 'App/USERS_RETRIEVED';
export const NEW_USER_CREATED = 'App/NEW_USER_CREATED';
export const ROLES_RETRIEVED = 'App/ROLES_RETRIEVED';
export const NEW_USER_ERROR_RETRIEVED = 'App/NEW_USER_ERROR_RETRIEVED';
export const PASSWORD_RESET = 'App/PASSWORD_RESET';
export const PASSWORD_RESET_ERROR = 'App/PASSWORD_RESET_ERROR';
export const RECIEVE_AUTH_URL = 'App/RECIEVE_AUTH_URL';
export const NEW_ROLE_CREATED = 'App/NEW_ROLE_CREATED';
export const NEW_ROLE_ERROR_RETRIEVED = 'App/NEW_ROLE_ERROR_RETRIEVED';

// -------- Upload Actions
export const UPLOAD_PENDING = 'App/UPLOAD_PENDING';
export const UPLOAD_SUCCESS = 'App/UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'App/UPLOAD_ERROR';
export const UPLOAD_DELETE = 'App/UPLOAD_DELETE';

// -------- Playbook Actions
export const PLAYBOOK_RETRIEVED = 'App/PLAYBOOK_RETRIEVED';
export const PLAYBOOK_SELECTED = 'App/PLAYBOOK_SELECTED';
export const SUBMITTED_PLAYBOOK_UPDATE = 'App/SUBMITTED_PLAYBOOK_UPDATE';

// -------- Playbook View Actions
export const TOGGLE_OPEN_CARD = 'App/TOGGLE_OPEN_CARD';
export const ADD_SLIDE = 'App/ADD_SLIDE';
export const REMOVE_SLIDE = 'App/REMOVE_SLIDE';
export const SAVING_PLAYBOOK = 'App/SAVING_PLAYBOOK';
export const PLAYBOOKS_RETRIEVED = 'App/PLAYBOOKS_RETRIEVED';
export const SINGLE_PLAYBOOK_RETRIEVED = 'App/SINGLE_PLAYBOOK_RETRIEVED';
export const EDIT_SLIDE = 'App/EDIT_SLIDE';
export const ADD_NEW_PLAYBOOK = 'App/ADD_NEW_PLAYBOOK';
export const UPDATE_MESSAGE = 'App/UPDATE_MESSAGE';
export const PLAYBOOK_MODIFIED = 'App/PLAYBOOK_MODIFIED';
export const PLAYBOOK_ORDER_MODIFIED = 'App/PLAYBOOK_ORDER_MODIFIED';
